project:
  type: website
  output-dir: docs

website:
  title: "Xavier Clemente García Cevallos"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: CV
        menu:
          - href: pages/cv/English.qmd
            text: English
          - href: pages/cv/Spanish.qmd
            text: pages/cv/Spanish
      - text: More
        menu:
          - href: pages/courses/Courses.qmd
            text: Courses
          - href: pages/divulgation/Divulgation.qmd
            text: Divulgation
      - href: pages/research/Research.qmd
        text: Research
      - href: pages/projects/Projects.qmd
        text: Projects
    right: 
      - icon: twitter
        href: https://x.com/clementegarcC
      - icon: linkedin
        href: https://www.linkedin.com/in/xavier-clemente-garc%C3%ADa-cevallos-b4727a206/
      - icon: github
        href: https://github.com/xavierclementegarcia 
      - text: '<img src="https://investigacion.udca.edu.co/wp-content/uploads/2018/04/cvlac.svg" alt="CLVAC" style="width: 20px; height: 20px;">'
        href: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0002018236
      - text: '<img src="https://upload.wikimedia.org/wikipedia/commons/0/06/ORCID_iD.svg" alt="ORCID" style="width:20px;height:20px;vertical-align:middle;">'
        href: https://orcid.org/0000-0002-3284-2363
  
  page-footer:
    left: |
      Xavier Clemente García Cevallos © 2025. All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

    center: 
      - icon: twitter
        href: https://x.com/clementegarcC
      - icon: linkedin
        href: https://www.linkedin.com/in/xavier-clemente-garc%C3%ADa-cevallos-b4727a206/
      - icon: github
        href: https://github.com/xavierclementegarcia
      - text: '<img src="https://investigacion.udca.edu.co/wp-content/uploads/2018/04/cvlac.svg" alt="CLVAC" style="width: 20px; height: 20px;">'
        href: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0002018236
      - text: '<img src="https://upload.wikimedia.org/wikipedia/commons/0/06/ORCID_iD.svg" alt="ORCID" style="width:20px;height:20px;vertical-align:middle;">'
        href: https://orcid.org/0000-0002-3284-2363
    right: |
      Made with <a href="https://www.r-project.org/"><img src="https://www.r-project.org/Rlogo.png" alt="R" width="25px"></a> 
      and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" alt="Quarto" width="65px"></a>.

format:
  html:
    theme: 
      light: 
      - sandstone
      dark: 
      - solar
    css: styles.css
    toc: true

editor: visual

