---
title: "Xavier Clemente García Cevallos"
subtitle: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: Xavier Clemente García Cevallos
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
xgarcia@unicauca.edu.co
:::

## EDUCATION

**B.S Biology Student** 
<br> 
*Cauca University* 
<br>
*Expected submission date: Nov 2026*
<br>
*GPA: 4.3/5.0*
<BR>
*GPA: 3.5/4.0*[Aug 2020 --- Present]{.cvdate}

## Courses & Certifications 

**Pre-Symposium Course. R with R for Biological Sciences**
<br> 
*Cauca University. XVII Symposium Biological Sciences Research *[November 2023 -- November 2023]{.cvdate}

**Ethnopharmacology and Ethnobotany: Biocultural transitions**
<br>
*Cauca University. Education, Naturals and Exact Sciences Faculty. Ethnobiological and Biocultural Studies Department.*[June 2023 -- June 2023]{.cvdate}

**DNA Discovery and Human Genome Project Competition**
<br>
*Cauca Univeristy. Education, Naturals and Exact Sciences Faculty*[April 2023 -- April 2023]{.cvdate}

**Molecular Models Bioinformatics**
<br>
*São Paulo University - USP*[November 2022 -- November 2022]{.cvdate}

**Botanical Scientific Drawing with an Ethnobiological Approach**
<br>
*Cauca University. Education, Naturals and Exact Sciences Faculty. Ethnobiological and Biocultural Studies Department*[December 2022 -- December 2022]{.cvdate}

**Handling tools in Microsoft Office Excel**
<br>
*National Learning Service SENA – Colombia*[September 2022 -- September 2022]{.cvdate}

**Control structures and Variables in Python**
<br>
*National Learning Service SENA – Colombia*[June 2022 -- July 2022]{.cvdate}

**The Chemestry of the Life**
<br>
*Kyoto University - KyotoUx*[March 2020 -- March 2021]{.cvdate}

## Conferences (Collaborations & Assistances)

**XVII Symposium in Sciences Biological Research**
<br>
*Cauca University (Collaborator)*[November 2023]{.cvdate}

**XI Latin American Congress of Medicinal Plants**
<br>
*COLAPLAMED. Quindío University (Assistant)*[September 2023]{.cvdate}

**International Colloquium: Omics Sciences, advances, big data and impact in personalized medicine and precision**
<br>
*Cauca University. Education, Naturals and Exact Sciences Faculty. Colombia (Assistant)*[November 2021]{.cvdate}

**XVI Research Symposium in Biological Sciences**
<br>
*Cauca University.Education, Naturals and Exact Sciences Faculty. Colombia (Assistant)*[November 2021]{.cvdate}

**COVID 19: An approach form Biology**
<br>
*University of Cauca. Education, Naturals and Exact Sciences Faculty. Colombia (Assistant)*[December 2020]{.cvdate}

## Work Experience
**Herbarium Collection Monitor at the Natural History Museum, University of Cauca**
<br>
*Description:*
<br>
*Support in the management and organization of the botanical material deposited in this institution. Guidance through the public collection of the Museum of Natural History (MHN) of the University of Cauca*[September 2024 -- Present]{.cvdate}

**Coordinator of the Research Seedbed in Developmental Biology and Neural Plasticity of Cauca University**
<br>
*Description:*
<br>
*Extracurricular space, made up of students and teachers, with the guidance of the mentor Dr. Willian Orlando Castillo Ordóñez. The purpose is to promote research culture through training for research focused mainly on undergraduate students, in one or different disciplinary areas, promoting creativity, innovation, commitment, social interaction, teamwork and social appropriation of knowledge about neurobiology. Mentor: Willian Orlando Castillo Ordoñez, PhD*[September 2024 -- Present]{.cvdate}

## Research Experience & Projects
**Interurban Biological Corridor Proposal in the Tulcan Sector in Popayan Municipality with Strategy for the conservation of the biodiversity and the territorial planification. (ID: 6114)**
<br>
*Cauca University.Education, Naturals and Exact Sciences Faculty. Biology Department. Nonvascular plants (Bryophytes) Taxonomy field. Project Chief: Professor Gisella Mabel Paz Perafán, Ph.D.*
<br>
*Description:*
<br>
*Sampling in the areas surrounding the Faculty of Natural, Exact and Educational Sciences of the University of Cauca. Quantification of the number of families, genera and species of Bryophytes. In this way, it is hoped to contribute to the knowledge of non-vascular plants for conservation and territorial planning purposes that may benefit the proposed interurban biological corridor in the Tulcán Sector of the Municipality of Popayán.*[January 2024 -- February 2025]


::: {.no-print}
## PRESENTATIONS AND WORKSHOPS
<br>
**Soon**

:::

::: {.print-only}
## References
Available upon request
:::
