---
title: "Curriculum Vitae"
date: last-modified
date-format: iso

author: 
  - name: Xavier Clemente García Cevallos
    email: xgarcia@unicauca.edu.co
    orcid: xxxxxxxx

address: "Popayán, Cauca"
email: xgarcia@unicauca.edu.co
github: xavierclementegarcia 
orcid: https://orcid.org/0000-0002-3284-2363 

theme:
  light: sandstone
  dark: solar

fontsize: 12pt
fontawesome: yes

format:
  html: 
    toc: true 
  quarto-cv-pdf: 
    default: true
    css: Spanish.css
---

### Resumen

Estudiante de Biología con sólida formación en áreas como biología molecular, fisiología vegetal, neurobiología y ecotoxicología. Manejo y gestión de colección botánica y herramientas computacionales aplicadas a la biología (modelos QSAR, bioinformática con R y Python).

### Educación

**Estudiante de Biología - Universidad del Cauca - (4.3)** \hfill [Aug 2020 - Presente]{.cvfloat}\

### Cursos y certificaciones

**Redacción científica en LaTeX e integración con R - Majuipal Solveris** \hfill [4 - 25 Feb 2025]{.cvfloat}\
Aprendizaje en la redacción de texto académicos a través de LaTeX.

**Investigación reproducible con Quarto - XII Congreso Colombiano de Botánica - Universidad del Cauca & Universidad de Antioquia** \hfill [3 - 4 Nov 2024]{.cvfloat}\

**Introducción a la investigación formativa: ¿Cómo investigar sin morir en el intento? - Vicerrectoría de Investigación Académica. Proyecto ECoS-CTel - Centro de Educación Continua, Abierta y Virtual (CECAV) - Universidad del Cauca** \hfill [31 - 12 Abr 2024]{.cvfloat}\

**Curso Pre Simposio. R con R para Ciencias Biológicas - XVII Simposio de Investigación en Ciencias Biológicas - Universidad del Cauca** \hfill [6-7 Nov 2023]{.cvfloat}\

**Etnofarmacología y Etnobotánica: Transiciones Bioculturales - Facultad de Educación, Ciencias Naturales y Exactas. Doctorado en Estudios Etnobiológicos y Bioculturales - Universidad del Cauca** \hfill [1 - 15 Junio 2023]{.cvfloat}\

**Modelación molecular - GBI Hands On: Modelagem Molecular - Facultad de Medicina de Ribeirão Preto, Universidad de São Paulo. Departamento de Genética. Bioinformática - Universidad de São Paulo (USP)** \hfill[24 - 25 Nov 2022]{.cvfloat}\

**Dibujo Científico Botánico con Abordaje Etnobiológico - Facultad de Educación, Ciencias Naturales y Exactas. Doctorado en Estudios Etnobiológicos y Bioculturales - Universidad del Cauca** \hfill [6 - 11 Dic 2022]{.cvfloat}\

**Manejo de herramientas en Microsoft Offices Excel 2016 - Servicio Nacional de Aprendizaje SENA - Colombia** \hfill [7 Agost-7 Sept 2021]{.cvfloat}\

**Estructuras de Control y Variables en Python - Servicio Nacional de Aprendizaje SENA - Colombia** \hfill [19 Jun-19 Jul 2022]{.cvfloat}\

**La química de la vida - Universidad de Kyoto - KyotoUx** \hfill [1 Mar 2021 - 1 Mar 2022]{.cvfloat}\

**Preparación de materiales y equipos básicos para laboratorio químico - Servicio Nacional de Aprendizaje SENA - Huila. Centro de Desarrollo Agroempresarial y pecuario del Huila - Colombia** \hfill [13 Sept-13 Dic 2016]{.cvfloat}\

### Conferencias

**Ciencia al parque - Mesa de Investigaciones Cauca** \hfill [24 - 25 Sept 2025]{.cvfloat}\

- **(Ponente)**Evaluación de efectos neuroreproductivos y morfológicos asociados a la exposición por Glifocafé en *Drosophila melanogaster* (Drosophilidae)

- **(Ponente)**Germinación de semillas de *Pterocaulon alopecuroides* (Lam.) DC.: aportes al conocimiento de especies nativas

**XVIII Simposio de Investigación en Ciencias Biológicas - Universidad del Cauca - Departamento de Biología** \hfill [15 - 19 Sept 2025]{.cvfloat}\

- **(Ponente)** QSAR preliminar de toxicidad mediante un modelo de aprendizaje supervisado en *Drosophila melanogaster* (Drosophilidae)

- **(Ponente)**Análisis *in silico* de metabolitos de *Peperomia* (Piperaceae) como potenciales moduladores de la enzima Pin1 en la enfermedad de Alzheimer: Estudio basado en ejemplares del Herbario CAUP.

- **(Ponente)**Efectos reproductivos, neurotóxicos y morfológicos de la exposición al Glifocafé en *Drosophila melanogaster* (Drosophilidae)

**52.º Congreso Socolen de Entomología Colombiana. Asociación Colombiana de Entomología - Universidad del Magdalena - Santa Marta, Magdalena, Colombia** \hfill [25 - 27 Jun 2025]{.cvfloat}\
**(Póster)** Expresión diferencial y evaluación *in silico* de pesticidas en rutas conductuales de *Atta cephalotes*

**I Encontro Científico Brasil - Colombia** \hfill [23 May 2025]{.cvfloat}\
**(Ponente)** *In vivo* and *in silico* evaluation of reproductive and neurotoxicity of *Erythroxylum coca* in *Drosophila melanogaster*

**XIII Encuentro de Investigación en Ciencias Biomédicas, Habilidades Morfológicas y Educación - Universidad de Durango, Sede Zacatecas, México** \hfill [26 May 2025]{.cvfloat}\

**(Póster)** Evaluación de los efectos neurotóxicos, reproductivos y morfológicos por exposición al Glifocafé® en *Drosophila melanogaster.*

**XIV Congreso Nacional XV Seminario Internacional de Neurociencias - Colegio Colombiano de Neurociencias - International Brain Research Organization - Pontificia Universidad Javeriana - Sede Bogotá.** \hfill [24 - 26 Abr 2025]{.cvfloat}\
**(Ponente)** Evaluación *in silico* del potencial terapeútico de *Pterocaulon alopecuroides* en la enfermedad de Alzheimer

**XII Congreso Colombiano de Botánica - Universidad del Cauca.** \hfill [4 - 8 Nov 2024]{.cvfloat}\
**(Organizador y Ponente)**

- **(Póster)** Viabilidad y capacidad germinativa en semillas de *Pterocaulon alopecuroides* (Lam.) DC.

- **(Ponente)** Biodiversidad de briofitas en la Universidad del Cauca, Popayán.

**Convergencia Regional del Pacífico para la COP-16 - Vicepresidencia de la República. Cali, Colombia** \hfill [25 - 26 Oct 2024]{.cvfloat}\
**(Ponente)** Staff MHN-Unicauca, Stand Cauca y Stand Economías Populares del distrito Pacífico en la zona verde de la COP16.

**XVII Simposio de Investigación en Ciencias Biológicas - Universidad del Cauca** \hfill [8 - 10 Nov 2023]{.cvfloat}\
**(Organizador)**

**XI Congreso Latinoamericano de Plantas Medicinales - Sociedad Latinoamericana de Plantas Medicinales (SOLAPLAMED) - Corporación Universitaria Santa Rosa de Cabal - Universidad del Quindío - Armenia, Quindío, Colombia.** \hfill [13 - 16 Sept 2023]{.cvfloat}\
**(Asistente)**

**II Simposio de Actualización en Cáncer: De la Genética a la Clínica - Universidad Militar de Nueva Granada - Bogotá,Cundinamarca, Colombia.** \hfill [3 Jun 2023]{.cvfloat}\
**(Asistente)**

**I Simposio de Células madre y terapia genética - Universidad Militar de Nueva Granada - Bogotá,Cundinamarca,Colombia.** \hfill [15 Abr 2023]{.cvfloat}\
**(Asistente)**

**Simposio en conmemoración del descubrimiento del ADN y el Proyecto Genoma Humano. Concurso por la molécula de ADN más precisa molecularmente - Red Iberoamericana de Inteligencia Artificial para Big BioData (RIABIO) - Grupo de Cáncer, Ambiental y Molecular (BIMAC) - Facultad de Educación, Ciencias Exactas y Naturales - Popayán, Cauca, Colombia.** \hfill [25 Abr 2023]{.cvfloat}\
**(Asistente)**

**Coloquio Internacional: Ciencias Ómicas, avances, big data e impacto en medicina personalizada y de precisión - Facultad de Educación, Ciencias Exactas y Naturales - Universidad del Cauca - Popayán, Cauca, Colombia.** \hfill [2 Nov 2021]{.cvfloat}\
**(Asistente)**

**XVI Simposio de Investigación en Ciencias Biológicas - Facultad de Ciencias Exactas y Naturales- Universidad del Cauca - Popayán, Cauca, Colombia.** \hfill [3 - 5 Nov 2021]{.cvfloat}\
**(Asistente)**

**COVID 19: Una aproximación desde la Biología - Facultad de Educación en Biología, Ciencias Exactas y Naturales de la Universidad del Cauca - Popayán, Cauca, Colombia.** \hfill [4 Dic 2020]{.cvfloat}\
**(Asistente)**

### Talleres dictados

**Introducción a R y manejo de pruebas estadísticas - Laboratorio de Entomología, Semillero Diversidad Funcional y Servicios Ecosistémicos (DIVERFUN) - Museo de Historia Natural - Universidad del Cauca, Popayán, Cauca, Colombia. (2 horas)** \hfill [5 Mar 2025]{.cvfloat}\
Este curso aborda criterios preliminares para comprender la lógica de programación, para luego profundizar en el conocimiento de librerías y paquetes fundamentales para que el biólogo pueda desarrollar análisis biológicos y diagramas de representación.

**Herramientas de inteligencia artificial para el manejo de R y ciencia reproducible - Semillero de Investigación en Geología, Ecología y Conservación - ASIO - Universidad del Cauca, Popayán, Cauca, Colombia (4 horas)** \hfill [16 May - Jun 2 2025]{.cvfloat}\
Este curso introduce el abordaje de la programación en el software R y cómo puedes resolver problemas difíciles de programación cuando comienzas a aprender sobre lógica de programación.

### Experiencia laboral

**Acreditación de programas de pregrado y posgrado acreditables RG 2022-009 a través del Centro de Gestión de la Calidad y la Acreditación institucional** \hfill [6 Abr - 6 Jul 2026]{.cvfloat}\
**(Monitor)** Apoyo en la sistematización de la información, organización de presentaciones y en el proceso de acreditación de alta calidad del programa de Biología

**Profesor particular de Biología y Química en Pre Universitario Smart, Popayán, Colombia** \hfill [1 Abr - 1 Jul 2026]{.cvfloat}\

**Profesor particular de Biología en Pre Universitario Next, Popayán, Colombia** \hfill [1 Abr - 1 May 2026]{.cvfloat}\

**Profesor freelance de lengua inglesa en Overcome The Barrier (OCTB)** \hfill [27 Nov 2025 - Presente]{.cvfloat}\

**Colección de Herbario en el Museo de Historia Natural, Universidad del Cauca** \hfill [2 Oct 2024 - 20 Jun 2025]{.cvfloat}\
**(Monitor)** Apoyo en la gestión, conservación y organización del material botánico depositado en el Herbario del Museo de Historia Natural (MHN) de la Universidad del Cauca.

**Semillero de Investigación en Biología del Desarrollo y Plasticidad Neural de la Universidad del Cauca** \hfill [10 Sept 2023 - Presente]{.cvfloat}\
**(Coordinador)** Apoyo, planificación y gestión dela organización de cursos, talleres y proyectos académicos.

### Experiencia en Investigación y Proyectos

**Propuesta de Corredor Biológico Interurbano en el Sector Tulcán del Municipio de Popayán con Estrategia para la conservación de la biodiversidad y el ordenamiento territorial. (ID: 6114) - Universidad del Cauca. Facultad de Educación, Ciencias Naturales y Exactas. Departamento de Biología. Área de Taxonomía de Plantas no vasculares (Briófitas).** \hfill [1 Ene - 30 Dic 2024]{.cvfloat}\
Cuantificar el número de familias, géneros y especies de Briófitos presentes en el secto Tulcán del Municipio de Popayán. Diseñar un plan de manejo para la consolidación de un corredor biológico interurbano en el sector Tulcán del Municipio de Popayán.

**Evaluación de la funcionalidad biológica de los extractos etanólico y acuoso de la hoja de coca. (ID: 6458) - Universidad del Cauca. Facultad de Educación, Ciencias Naturales y Exactas** \hfill [29 agost 2025 - 28 agost 2026]{.cvfloat}\
Determinación de la citotoxicidad/genotoxicidad de extractos acuosos y etanólicos, simular interacciones moleculares con proteínas patológicas y modelar cambios conformacionales mediante dinámica molecular para el descubrimiento de nuevos compuestos biológicamente activos.

### Premios y distinciones

**Reconocimiento al Mérito Institucional – Rectoría de la Universidad del Cauca** \hfill [2 Nov 2025]{.cvfloat}\
Otorgado por el Rector de la Universidad por contribuciones académicas y de investigación destacadas en el marco del 198.º Aniversario de la institución. Esta distinción representa el máximo honor institucional a la excelencia estudiantil.

**XIII Encuentro de Investigación en Ciencias Biomédicas, Habilidades Morfológicas y Educación - Universidad de Durango, Campus Zacatecas, México.** \hfill [2 Junio 2025]{.cvfloat}\
**Distinción** Primer puesto en modalidad póster al trabajo "Evaluación de los efectos neurotóxicos, reproductivos y morfológicos por exposición al Glifocafé® en *Drosophila melanogaster*".

**XIV Congreso Nacional de Neurociencias y XV Seminario Internacional de Neurociencias - Bogotá, Cundinamarca, Colombia.** \hfill [23 Abril 2025]{.cvfloat}\
**Honor:** Beca IBRO - Exención de pago de inscripción al XIV Congreso Nacional de Neurociencias y XV Seminario Internacional de Neurociencias - Bogotá, Cundinamarca, Colombia.

**Simposio para conmemorar el descubrimiento del ADN y el Proyecto Genoma Humano. Concurso para la molécula de ADN más precisa molecularmente.** \hfill [25 Abril 2023]{.cvfloat}\
**Distinción:** Primer puesto por desempeño destacado en la construcción de la Molécula de ADN \# Artículos en preparación García Cevallos, X. C., Castillo Bravo, C. C., Tovar, Y. Y., Giraldo Aristizábal, C. I., & Castillo Ordóñez, W. O. Evolutionary divergence of 1,3-β-glucan synthase and its impact on the binding affinity of natural compounds with potential antifungal activity: An in silico approach.

### Aptitudes

**Idiomas**

- Español (nativo), Inglés (B2), Portugués (A1)

**Informáticas**

Experiencia en el manejo de sistemas operativos Linux, macOS y Windows. Competencias en acoplamiento molecular y simulaciones de dinámica molecular, evaluación de perfiles ADMET, modelado QSAR, análisis filogenéticos y transcriptómicos (DESeq2), así como programación científica en Python, R, C, Rust y Bash. Experiencia en la redacción científica y el desarrollo de documentos reproducibles mediante LaTeX, Markdown y Quarto.

**Educativas**

Conocimientos en biología y química, con experiencia en la enseñanza y divulgación de conceptos de biología celular, molecular, genética, botánica, bioquímica y química general. Capacidad para diseñar y desarrollar materiales educativos, impartir talleres y cursos, y comunicar contenidos científicos de forma clara y adaptada a diferentes públicos.

**Investigación científica**

Diseño y ejecución de proyectos de investigación en biología, con experiencia en desarrollo de protocolos e interpretación de resultados experimentales y computacionales

**Técnicas**

Extracción, procesamiento de metabolitos vegetales mediante Soxhlet, Ultrasonido y técnicas semicuantitativas de tamizaje fitoquímico.

Experiencia en el manejo, estandarización y validación de datos de biodiversidad mediante el estándar Darwin Core (DwC), así como en la organización, curación e integración de bases de datos biológicas para investigación, monitoreo y análisis de información taxonómica y de distribución de especies.

**Comunicación científica**

Redacción y organización de literatura científica

### Artículos en preparación

García Cevallos, X. C., Castillo Bravo, C. C., Tovar, Y. Y., Giraldo Aristizábal, C. I. & Castillo Ordóñez, W. O. Evolutionary divergence of 1,3-β-glucan synthase and its impact on the binding affinity of natural compounds with potential antifungal activity: An *in silico* approach.

### Artículos en revisión

García Cevallos, X. C., Huila Medina, J. F., Muñoz Buitrón, D., & Arcos, L. T., *(En revisión)*, Efectos reproductivos, neurotóxicos y morfológicos de la exposición al Glifocafé® en *Drosophila melanogaster*

### Artículos publicados

Polindara Moncayo, Y. W., Garcia Cevallos, X.C, Guevara Trujillo, D.T., Viabilidad y capacidad germinativa en semillas de *Pterocaulon alopecuroides* (Lam) DC planta de uso medicinal.DOI: https://doi.org/10.14483/2256201X.23642

### Asociaciones

**Grupo de Investigación en Microscopía y Análisis de Imágenes (GIMAI) - Investigador**\
**Semillero de Biología del Desarrollo y Plasticidad Neural - Coordinador**\
**Biosis Talks - Fundador**\
**Instituto Colombiano de Neurociencias - Socio activo**\
**Asociación Latinoamericana de Biología Sintética - Comité de expansión**\
**Asociación Colombiana de Botánica - Socio activo** \

::: print-only\
### Referencias

Disponible a solicitud
:::
